In [2]:
#youtube.com/watch?v=2S1dgHpqCdk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz
#Aladdin's Tutorial
import torch
import torch.nn as nn
import numpy as np

In [3]:
# basic tensor and gpu
device = "cuda" if torch.cuda.is_available() else "cpu" #check availability
data_here = [[1,2,3], [4,5,6]]
my_tensor = torch.tensor([data_here], dtype = torch.float32,
                         device= device, #if 0==0 else "cuda"
                         requires_grad=True) # autograd
# cuda or cpu
print(my_tensor)
# .dtype and .device

tensor([[[1., 2., 3.],
         [4., 5., 6.]]], requires_grad=True)


In [4]:
print(f'{my_tensor} has {my_tensor.dtype} and \
 is on device \n {my_tensor.device} respectively. \
 The tensor has shape {my_tensor.shape} and the option for autograd is {my_tensor.requires_grad}')
# .dtype and .device respectively

tensor([[[1., 2., 3.],
         [4., 5., 6.]]], requires_grad=True) has torch.float32 and  is on device 
 cpu respectively.  The tensor has shape torch.Size([1, 2, 3]) and the option for autograd is True


In [5]:
x = torch.empty(size = (3,3)) # like np.random
x = torch.zeros((3,3)) #like np.zeros(tuple)
x = torch.rand((3,3)) #np.random - normal
x = torch.ones((3,3)) #like np.ones
x = torch.eye(5,5) # like np.eye

#range-type  functions have start, end, and steps
x = torch.arange(start=0, end=5, step = 1) # like np arange and range *python
print(x)
x = torch.linspace(start=0.1, end=1, steps=10) #like np.linspace
#torch.empty has initializing functions ending with _, such as uniform_ and normal_
x = torch.empty(size=(6,9)).normal_(mean=0, std=1)
x = torch.empty(size=(6,9)).uniform_(0, 1)

x = torch.diag(torch.ones(3)) # Create diagonal of ones, special - identity/eye
y = np.diag([[0,1,2], [3,4,5], [6,7,8]]) #extract diagonal

#tensor type conversions - explicit
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
#float double half

# conversions np and torch
np_tensor = tensor.numpy()
tensor = torch.from_numpy(np_tensor)

tensor([0, 1, 2, 3, 4])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])


In [6]:
# Math and <= operations

#corresponding inplace operations by operation_ and python overloaded ie. torch.add(x, y, out=z) -> x+y -> x.add_
#subtracion
c = torch.empty(3) #placeholder with shape of output
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
print(x+y)
print(torch.add(x, y))
print(x.add_(y))
#Subtraction
print(torch.subtract(x,y))
#...
print(torch.multiply(x,y))

#division
print(torch.divide(x,y))
print(torch.true_divide(x,y))



tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([1, 2, 3])
tensor([20, 35, 54])
tensor([1.2500, 1.4000, 1.5000])
tensor([1.2500, 1.4000, 1.5000])


In [7]:
#little test
x = torch.tensor([1,2,3], dtype=torch.float32)
y = x*3+3

In [8]:
print(y)

tensor([ 6.,  9., 12.])


In [9]:
n = 3

w = torch.rand((1, n ))
b = torch.rand((1, n))
print(x.size())
print((x*w+b).size())

torch.Size([3])
torch.Size([1, 3])


In [10]:
def loss_function(x, y_pred, y):
  print(x.shape)
  J = torch.sum(torch.subtract(y_pred, y) ** 2)/n
  return (J*x, J)

In [11]:
epsilon = 1e-4
for i in range(1000):
  y_pred = x * w + b
  dw, db = loss_function(x, y_pred, y)
  w = torch.subtract(epsilon*dw, w)
  b = torch.subtract(epsilon*db, b)


torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Si

In [12]:


# versus element mult
z = x*y
print(z)

# dot product sum(element mult)
z = torch.dot(x, y)
print(z)

#mm
x1 = torch.rand((3,4))
x2 = torch.rand((4, 6))
x3 = torch.mm(x1, x2) # matrix mult
x3 = x1.mm(x2)

# batch mm
# add extra dimension for batch - use bmm instead of mm
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand(batch, n, m) # same thing, m must match for matrix mult
tensor2 = torch.rand(batch, m, p)
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm)

#broadcasting in pytorch, numpy, tf

tensor([ 6., 18., 36.])
tensor(60.)
tensor([[[4.7743, 4.9023, 6.8897,  ..., 5.1805, 5.0233, 3.6928],
         [4.9822, 3.7150, 5.5492,  ..., 4.2282, 4.8526, 3.8588],
         [4.1996, 3.9166, 5.7912,  ..., 3.8364, 3.4248, 2.7072],
         ...,
         [7.4558, 6.2413, 8.4410,  ..., 6.3215, 6.0238, 4.0327],
         [5.1266, 5.2728, 5.2049,  ..., 4.7469, 5.1193, 3.3715],
         [6.7506, 5.4785, 6.8038,  ..., 6.0181, 5.6936, 4.6214]],

        [[6.8539, 6.2841, 5.9942,  ..., 5.9012, 6.8111, 5.7208],
         [5.5667, 5.0442, 5.4811,  ..., 5.7017, 6.3862, 5.8638],
         [5.0092, 5.5013, 4.2644,  ..., 4.8522, 5.6181, 4.8725],
         ...,
         [4.4146, 4.7781, 3.6597,  ..., 4.4554, 4.9067, 4.4331],
         [4.9785, 4.9584, 4.9365,  ..., 4.7995, 5.7719, 4.4821],
         [5.8431, 5.2544, 5.5171,  ..., 5.9240, 6.3597, 5.1362]],

        [[4.5655, 3.3265, 4.0628,  ..., 4.1559, 4.5639, 3.9459],
         [4.8227, 4.4629, 3.6379,  ..., 3.7589, 4.5820, 4.2322],
         [5.3811, 3.45

In [ ]:
#Matrix exp
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[1.3724, 1.7565, 1.1676, 1.1139, 0.8417],
        [2.4375, 2.8066, 1.8899, 2.1555, 1.4540],
        [3.7882, 4.7020, 3.1175, 3.4549, 2.0689],
        [2.2655, 2.6990, 1.7720, 1.9178, 1.2984],
        [1.9440, 2.2404, 1.6193, 1.6873, 1.1709]])


In [16]:
# useful math functions
#sum, max, dim, take x and dim= on dimension specified, argmax/min return index
#abs input
mean_x  = torch.mean(x.float(), dim=0) # requires float

#comparison
z = torch.eq(x,y)
print(z)

sorted_y, indices = torch.sort(y, dim=0, descending=False) # sort on dim, descending False -> ascend
z = torch.clamp(x, min=0, max=10) # set less than or greater than to ceil/floor
x = torch

# boolean operations
x = torch.tensor([1,0,0,1,1], dtype=torch.bool)
z = torch.any(z)# multiple or st
z = torch.all(z) # and multiple

#for functions, also same methods - input
#ie. torch.max(x, dim=0) -> x.max(dim=0)

tensor([False, False, False])


In [17]:
gradient = torch.clamp(x, max=1) # g clip

In [21]:
#indices operations
#assignment and access same as python
#.shape -> shape
#can use list of indices -> x[indices]

#boolean operations (advanced)
my_list = torch.arange(10)
print(my_list[(my_list < 2) | (my_list>8)])
#x.remainder(2) -> returns quotient of x/2 numbers - even

print(torch.where(z>5, z, z*2)) # compare to tf.where
# condition, true, false
#.unique() gets unique
#.ndimension() return dim
#.numel() #number ofelements

tensor([0, 1, 9])
tensor(2)


In [26]:
d = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
e = torch.tensor([[4,5], [6,7], [8,9]], dtype=torch.float32)
f = d.mm(e)

In [27]:
print(f.numel())
print(f.ndimension())
print(f.unique())

4
2
tensor([ 40.,  46.,  94., 109.])


In [29]:
#reshaping
x = torch.arange(9)
#view and reshape similar, view - contiguous tensor, reshape doesn't - perform loss
x_3x3 = x.view(3,3)
x_3x3 = x.reshape(3,3)
print(x_3x3)

#transpose - .t() - not contiguous
y = x_3x3.t()
print(y)
#print(y.view()) # doesn't work
print(y.contiguous().view(9)) # make contiguous

#.cat(shape=)
#flatten to 1d
x.reshape(-1)
#flatten on a dim / custom dim
#batch, 2, 5, -> batch, -1 -> batch, 10

# inverse of flatten
x.unsqueeze(0) # dimension index to expand on


# swap dim
#ie. matrix of 25, 1, 2 -> 25, 2, 1
z = x.permute(0, 2, 1) # for dimensions, put in indices


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


RuntimeError: ignored